stages:
  - lint
  - build
  - serve

lint-job:
  stage: lint
  script:
    - cd ros_web
    - npm run lint
  only:
    - web
  tags:
    - ubuntu_try

build-job:
  stage: build
  script:
    - cd ros_web
    - npm install
    - npm run build
  only:
    - web
  tags:
    - ubuntu_try

serve-job:
  stage: serve
  script:
    - cd ros_web
    - npm run serve
  only:
    - web
  tags:
    - ubuntu_try
